apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName}}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: nodejs-app
          image: "{{ .Values.image.repository}}:{{ .Values.image.tag}}"
          ports:
            - containerPort: {{.Values.container.port}}
          envFrom:
            - secretRef:
                name: db-secret

